Michael  cynthia/#62/app registration pages
Amaris-Digital/fariji pull request #72
Opened 2023-06-04 16:01 UTC by chelahcynthia

This PR registers new users.

2023-06-04 18:49 UTC, chelahcynthia commented
Managed to fix the lint errors. I'll be waiting for the review

2023-06-05 02:03 UTC, otsembo requested changes
Hello @chelahcynthia @MICHAELMUNAVU83 Good job on the PR.
I have requested minor changes to the PR.

I will add my code to the PR by tomorrow, Tuesday 6 June EOD.

2023-06-05 02:03 UTC, otsembo commented on client/src/App.tsx
> +// ]);
Remove unnecessary comment from code

2023-06-05 02:03 UTC, otsembo commented on client/src/pages/Registration.tsx
> +        <p>Sign In</p>
Add some whitespace between `Already have an account?` and `Sign In`.

2023-06-08 13:23 UTC, otsembo requested changes
Hello @chelahcynthia @MICHAELMUNAVU83 Great job on this PR.
Apologies for not sending in this review earlier, I was facing some small blocker with the codebase but that is now fixed.

# FIXES
Check on the following:

- [ ] The Add photo functionality does not seem to be working correctly.
- [ ] A user is able to swipe right even if the register process fails. This should not be the case. Find a way to prevent this from happening.
- [ ] The `reason for joining` section also does not seem to work. Kindly check on this as well.
- [ ] Once the reason for joining is clicked, it should be highlighted so that the user can be able to know which button they have clicked.

# ENHANCEMENTS
The screen does not scale well in larger screens. Kindly find a way to sort this out. You can acquire inspiration from what the guys working on `login` did.
![image](https://github.com/Amaris-Digital/fariji/assets/38042565/6823fd64-995d-46a4-b44a-f7a6ce673b7e)

**NB: Make sure you pull the changes made, since I have added quite a large number of them**

I have also added a few more lint checkers and code style actions. I have also updated the `README` with some new instructions on how to use them.

cc @timothykiyeng => You can help out with the upload section for images here.

2023-06-08 13:23 UTC, otsembo commented on .DS_Store
Remove this file from version control.

2023-06-12 05:14 UTC, otsembo requested changes
Hello @MICHAELMUNAVU83 
You seem to be having a failing check on the PR.
Have a look at that.

2023-06-12 18:07 UTC, MICHAELMUNAVU83 commented
Hello @otsembo  , I have fixed the error present .

2023-06-13 08:09 UTC, otsembo requested changes
Hello @MICHAELMUNAVU83 
There seems to be an issue with how the app navigation works when creating an account.
[Video](https://github.com/Amaris-Digital/fariji/assets/38042565/b0531535-5045-4283-97e1-390354e70031)

# FIXES

- [x] The `Exit` action returns the page to previous slide as opposed to resetting to the initial page.
- [x] Once an error occurs during registration, the page still navigates to the next slide regardless, this should not be the case. Ensure you confirm that the error is non-existent before moving to the next page.

2023-06-13 17:38 UTC, MICHAELMUNAVU83 commented
Hello @otsembo  , I have been able to do the exit feature but I have struggled with the other one , any help accorded would be greatly appreciated .

2023-06-15 02:50 UTC, otsembo approved these changes
Everything looks good.

2023-06-15 02:51 UTC, merged