Tosh-Mackrine/#85/view user profile data
Amaris-Digital/fariji pull request #90
Opened 2023-07-03 13:54 UTC by Muriithi-Gitonga

#### This PR contains:
-  User profile query and the tests

2023-07-04 06:35 UTC, otsembo requested changes
Hello @Muriithi-Gitonga @mackrineawino Great job on the PR.
I have left a few comments on things you can fix.

@Kimutai01 @naomirono Kindly make your reviews on this.

2023-07-04 06:35 UTC, otsembo commented on api/spec/graphql/query/profile_spec.rb
> +                pp json
Remove unnecessary print.

2023-07-04 06:35 UTC, otsembo commented on api/spec/graphql/query/profile_spec.rb
> +                pp json
Remove unnecessary print.

2023-07-04 06:35 UTC, otsembo commented on api/db/seeds.rb
> +puts "Done seeding"
We do not need any seeding data in production for now. You can omit this from version control for now.

2023-07-04 06:35 UTC, otsembo commented on api/spec/graphql/query/profile_spec.rb
> +RSpec.describe 'user mutation', type: :request do
You are describing a `query` as opposed to `mutation`. Kindly fix the naming.

2023-07-04 07:17 UTC, mackrineawino commented
> Hello @Muriithi-Gitonga @mackrineawino Great job on the PR. I have left a few comments on things you can fix.
> 
> @Kimutai01 @naomirono Kindly make your reviews on this.

Hello @otsembo  we have made the requested changes. Kindly check.

2023-07-04 08:03 UTC, Kimutai01 approved these changes
hello @Muriithi-Gitonga and @mackrineawino,
Good job on making the changes requested before. 
Everything works well

2023-07-05 04:51 UTC, otsembo approved these changes
Everything looks good now. Great job @Muriithi-Gitonga @mackrineawino

2023-07-05 08:37 UTC, naomirono approved these changes

2023-07-06 07:53 UTC, merged